### ISSUE TITLE
cannot create the notebook

### ISSUE THREAD

**Issue by zamrokk** [IBM/dsx-twitter-auto-analysis#31]
on the step to create the notebook on Bluemix, i have an error.

I can see on the browser console that there is a CORS issue ?

![image](https://cloud.githubusercontent.com/assets/2536368/26156060/5f8f7a44-3b15-11e7-935a-9dcab9947607.png)

**Comment by stevemar** [comment]
hey @zamrokk -- thanks for reporting the issue, exactly what URL are you using? I noticed that if I have a leading white space it doesn't load, but using ``https://github.com/IBM/dsx-twitter-auto-analysis/blob/master/notebooks/dsx_twitter_auto_analysis.ipynb`` works just fine.

**Comment by zamrokk** [comment]
It looks ok now, i did another copy paste

Maybe a space somewhere ?

Thx anyway
