### ISSUE TITLE
Service offering twitterinsights not found

### ISSUE THREAD

**Issue by lee-zhg** [IBM/dsx-twitter-auto-analysis#39]
Creating service instance dtaa-twitter-service in org zhangllc@outlook.com / space dev as XYZ 
FAILED
Service offering twitterinsights not found

Finished: FAILED

**Comment by stevemar** [comment]
So we've been struggling with this for a while now, see the other referenced bugs. The "insights for twitter" service was retired in the middle of last year [1]. We intended to use a service called gnip [2], but ran into issues with registration and didn't want our users to also run into these issues. 

Unfortunately we didn't have a running service to copy the tweets and check them into repo and haven't found a similar service that could scrape the data the same way "insights for twitter" did.

We have a few choices:

1. archive this repository and remove the code pattern entirely from ibm code site
1. leave this repository up but clearly mark it as deprecated in the README, I'm wondering if people will still find value in the notebook that is checked in
1. find an alternative service that loads twitter data

I'm open to any of these...

[1] https://www.ibm.com/blogs/bluemix/2017/03/retirement-insights-twitter-service/
[2] https://www.gnip.com

**Comment by stevemar** [comment]
We've officially made this repo obsolete, refer to the latest README
